export type CountryOption = {
  code: string;
  name: string;
  flag: string;
  flagUrl: string;
};

// ISO 3166-1 alpha-2 codes. The display name is generated by the browser's
// locale data so the picker stays compact while still covering every country.
const COUNTRY_CODES = `
  AF AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MK MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW AX
`
  .trim()
  .split(/\s+/);

const regionNames = new Intl.DisplayNames(['es'], { type: 'region' });

function countryFlag(code: string): string {
  return code
    .split('')
    .map((letter) => String.fromCodePoint(127397 + letter.charCodeAt(0)))
    .join('');
}

export const COUNTRIES: CountryOption[] = COUNTRY_CODES.map((code) => {
  const name = regionNames.of(code);
  return name
    ? {
        code,
        name,
        flag: countryFlag(code),
        flagUrl: `https://flagcdn.com/w40/${code.toLowerCase()}.png`,
      }
    : null;
})
  .filter((country): country is CountryOption => Boolean(country))
  .sort((a, b) => a.name.localeCompare(b.name, 'es'));

export function normalizeCountryName(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase('es')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

export function findCountryByName(value: string | null | undefined) {
  if (!value) return undefined;
  const normalized = normalizeCountryName(value);
  return COUNTRIES.find(
    (country) => normalizeCountryName(country.name) === normalized
  );
}
